name: RosenRed
favicon: null
layout_spectrum: 0.70878
typography_spectrum: 0.85103
title: digital design sketchbook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#590000'
    - '#130000'
    - '#c11117'
    - '#323534'
    - '#fc3538'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
