name: RosenRed
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85103
title: RosenRed Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#590000'
    - '#130000'
    - '#c11117'
    - '#323534'
    - '#fc3538'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
