name: RosenRed
favicon: null
layout_spectrum: 0.9830223524477333
typography_spectrum: 0.8354819647502154
title: RosenRed Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#590000'
    - '#130000'
    - '#c11117'
    - '#323534'
    - '#fc3538'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
